version: 0.1
phases:
    install:
        commands:
            - 'touch .npmignore'
            - 'npm install -g gatsby'
    pre_build:
        commands:
            - 'npm ci --production'
    build:
        commands:
            - 'npm run-script build'
    post_build:
        commands:
            - 'npm run-script deploy'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: no
cache:
    paths:
        - '.cache/*'
        - 'public/*'